# Generated by Django 5.1.7 on 2025-03-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default='Guest', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='0000000000', max_length=15),
        ),
    ]
