# Generated by Django 5.1.7 on 2025-03-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_alter_order_mobile_alter_order_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
