# Generated by Django 5.1.7 on 2025-05-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_menuitem_is_available_alter_menuitem_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='token_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
